const ListWarga = [
  {
    _id: '1',
    no_ktp: '7171090907370009',
    no_keluarga: '911',
    nama: 'Eston Suli',
    agama: 'Kristen Protestan',
    t_lahir: 'Manado',
    tanggal_lahir: '08/17/2000',
    j_kelamin: 'Laki-Laki',
    gol_darah: 'AB',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Mahasiswa',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '2',
    no_ktp: '7171090907370019',
    no_keluarga: '456',
    nama: 'DEETJE C. TINDANGEN',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '11/20/1949',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Ibu Rumah Tangga',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '3',
    no_ktp: '7171090907370029',
    no_keluarga: '456',
    nama: 'CHANAN MACHFUDI',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '12/2/1989',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Nelayan',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '4',
    no_ktp: '7171090907370039',
    no_keluarga: '456',
    nama: 'CHARLES V. JACOBUS',
    agama: 'Hindu',
    t_lahir: 'Manado',
    tanggal_lahir: '12/8/1989',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'China',
    pendidikan: 'S1',
    pekerjaan: 'Nelayan',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '5',
    no_ktp: '7171090907370079',
    no_keluarga: '456',
    nama: 'CHANAN MACHFUDI',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '10/2/1989',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Pelaut',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '6',
    no_ktp: '7171090907370027',
    no_keluarga: '456',
    nama: 'CHATOTJE KALIGIS',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '8/2/1999',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S2',
    pekerjaan: 'Pegawai Negeri Sipil',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '7',
    no_ktp: '7171090907370034',
    no_keluarga: '456',
    nama: 'DEITJE SERO',
    agama: 'Khatolik',
    t_lahir: 'Manado',
    tanggal_lahir: '12/2/1989',
    j_kelamin: 'Laki-Laki',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Pensiunan',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '8',
    no_ktp: '7171090907372049',
    no_keluarga: '456',
    nama: 'DOLFINES RATOWO',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '9/22/1989',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Nelayan',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '9',
    no_ktp: '7171090907330529',
    no_keluarga: '456',
    nama: 'EDWARD LENDIE TUMBELAKA',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '3/2/1969',
    j_kelamin: 'Laki-Laki',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Belum Bekerja',
    s_nikah: 'Belum',
    status: 'Hidup',
  },
  {
    _id: '10',
    no_ktp: '7171090907330729',
    no_keluarga: '456',
    nama: 'ELSJE MARIE MAIT',
    agama: 'Islam',
    t_lahir: 'Manado',
    tanggal_lahir: '6/3/1989',
    j_kelamin: 'Perempuan',
    gol_darah: 'A',
    w_negara: 'Indonesia',
    pendidikan: 'S1',
    pekerjaan: 'Belum Bekerja',
    s_nikah: 'Sudah',
    status: 'Hidup',
  },
];

export default ListWarga;
