export const KELUARGA_LIST_REQUEST = 'KELUARGA_LIST_REQUEST';
export const KELUARGA_LIST_SUCCESS = 'KELUARGA_LIST_SUCCESS';
export const KELUARGA_LIST_FAIL = 'KELUARGA_LIST_FAIL';

export const KELUARGA_DETAILS_REQUEST = 'KELUARGA_DETAILS_REQUEST';
export const KELUARGA_DETAILS_SUCCESS = 'KELUARGA_DETAILS_SUCCESS';
export const KELUARGA_DETAILS_FAIL = 'KELUARGA_DETAILS_FAIL';
export const KELUARGA_DETAILS_RESET = 'KELUARGA_DETAILS_RESET';

export const KELUARGA_CREATE_REQUEST = 'KELUARGA_CREATE_REQUEST';
export const KELUARGA_CREATE_SUCCESS = 'KELUARGA_CREATE_SUCCESS';
export const KELUARGA_CREATE_FAIL = 'KELUARGA_CREATE_FAIL';
export const KELUARGA_CREATE_RESET = 'KELUARGA_CREATE_RESET';

export const KELUARGA_DELETE_REQUEST = 'KELUARGA_DELETE_REQUEST';
export const KELUARGA_DELETE_SUCCESS = 'KELUARGA_DELETE_SUCCESS';
export const KELUARGA_DELETE_FAIL = 'KELUARGA_DELETE_FAIL';

export const KELUARGA_UPDATE_REQUEST = 'KELUARGA_UPDATE_REQUEST';
export const KELUARGA_UPDATE_SUCCESS = 'KELUARGA_UPDATE_SUCCESS';
export const KELUARGA_UPDATE_FAIL = 'KELUARGA_UPDATE_FAIL';
export const KELUARGA_UPDATE_RESET = 'KELUARGA_UPDATE_RESET';
