export const WARGA_LIST_REQUEST = 'WARGA_LIST_REQUEST';
export const WARGA_LIST_SUCCESS = 'WARGA_LIST_SUCCESS';
export const WARGA_LIST_FAIL = 'WARGA_LIST_FAIL';

export const WARGA_DETAILS_REQUEST = 'WARGA_DETAILS_REQUEST';
export const WARGA_DETAILS_SUCCESS = 'WARGA_DETAILS_SUCCESS';
export const WARGA_DETAILS_FAIL = 'WARGA_DETAILS_FAIL';

export const WARGA_DELETE_REQUEST = 'WARGA_DELETE_REQUEST';
export const WARGA_DELETE_SUCCESS = 'WARGA_DELETE_SUCCESS';
export const WARGA_DELETE_FAIL = 'WARGA_DELETE_FAIL';

export const WARGA_CREATE_REQUEST = 'WARGA_CREATE_REQUEST';
export const WARGA_CREATE_SUCCESS = 'WARGA_CREATE_SUCCESS';
export const WARGA_CREATE_FAIL = 'WARGA_CREATE_FAIL';
export const WARGA_CREATE_RESET = 'WARGA_CREATE_RESET';

export const WARGA_UPDATE_REQUEST = 'WARGA_UPDATE_REQUEST';
export const WARGA_UPDATE_SUCCESS = 'WARGA_UPDATE_SUCCESS';
export const WARGA_UPDATE_FAIL = 'WARGA_UPDATE_FAIL';
export const WARGA_UPDATE_RESET = 'WARGA_UPDATE_RESET';
