export const WARGA_LIST_REQUEST = 'WARGA_LIST_REQUEST';
export const WARGA_LIST_SUCCESS = 'WARGA_LIST_SUCCESS';
export const WARGA_LIST_FAIL = 'WARGA_LIST_FAIL';

export const WARGA_DETAILS_REQUEST = 'WARGA_DETAILS_REQUEST';
export const WARGA_DETAILS_SUCCESS = 'WARGA_DETAILS_SUCCESS';
export const WARGA_DETAILS_FAIL = 'WARGA_DETAILS_FAIL';
